# Generated by Django 4.0.6 on 2023-10-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacoes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
